language: node_js
node_js:
  - "11.10.1"

services:
  - mongodb

env:
  global:
    - DB_HOST=localhost
    - DB_PORT=27017
    - DB_NAME=moneybunney
    - REACT_APP_BACKEND_HOST=localhost
    - REACT_APP_BACKEND_PORT=8080
    - REACT_APP_HOST=localhost
    - REACT_APP_PORT=3000

install:
  - npm --prefix ./frontend install
  - npm --prefix ./backend install

script:
  - npm --prefix ./frontend run build
  - npm --prefix ./backend run build
  - npm --prefix ./frontend run test --no-watch
  - npm --prefix ./backend run test
