language: node_js
node_js:
  - "11.10.1"

services:
  - mongodb

install:
  - npm --prefix ./frontend install
  - npm --prefix ./backend install

# No idea if this is correct
script:
  - npm --prefix ./frontend run build
  - npm --prefix ./backend run build
  - npm --prefix ./frontend run test --no-watch
  - npm --prefix ./backend run test