language: node_js
node_js:
  - "11.10.1"

services:
  - mongodb

env:
  global:
    - DB_HOST=localhost
    - DB_PORT=27017
    - DB_NAME=moneybunney
    - REACT_APP_API_HOST=localhost
    - REACT_APP_API_PORT=8080

install:
  - npm --prefix ./frontend install
  - npm --prefix ./backend install

# No idea if this is correct
script:
  - npm --prefix ./frontend run build
  - npm --prefix ./backend run build
  - npm --prefix ./frontend run test --no-watch
  - npm --prefix ./backend run test
