version: "3.2"

services:
  db:
    image: mongo:latest
    command: mongod --port 27023
    ports:
      - "27023:27023"
    volumes:
      - type: volume
        source: db-data
        target: /data/db

  backend:
    build:
      dockerfile: backend.Dockerfile
      context: ./
    ports:
      - "8081:8081"
    depends_on:
      - "db"
    environment:
      - DB_HOST=db
      - DB_PORT=27023
      - DB_NAME=moneybunney

  frontend:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - "backend"
    environment:
      - REACT_APP_API_HOST=localhost
      - REACT_APP_API_PORT=8081

volumes:
  db-data:
