version: "3"

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=moneybunney

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - "backend"
    environment:
      - API_HOST=backend
      - API_PORT=8080
