version: '3'

services:
    db:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db

    backend:
        build: ./backend
        ports:
            - "8080:8080"
        depends_on:
            - "db"

    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - "backend"
