version: "3.2"

services:
  db:
    image: mongo:latest
    env_file: .env
    command: mongod --port ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - type: volume
        source: db-data
        target: /data/db

  backend:
    env_file: .env
    build:
      dockerfile: backend.Dockerfile
      context: ./
      args:
        port: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - "db"
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=moneybunney
      - REACT_APP_PORT=${REACT_APP_PORT}
      - REACT_APP_HOST=${REACT_APP_HOST}

  frontend:
    env_file: .env
    build:
      context: ./
      dockerfile: frontend.Dockerfile
      args:
        port: ${REACT_APP_PORT}
    command:
      - npm
      - run
      - start
    # command:
    #   - npm
    #   - run
    #   - start:prod
    #   - --
    #   - -l
    #   - ${REACT_APP_PORT}
    #   - build
    ports:
      - "${REACT_APP_PORT}:${REACT_APP_PORT}"
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - TEST=test
    depends_on:
      - "backend"

volumes:
  db-data:
